apiVersion: apps/v1
kind: Deployment
metadata:
    name: Devops
    namespace: project1
    labels:
        app: Devops
spec:
    replicas: 3
    selector:
        matchLabels:
            app: Devops
    template:
        metadata:
            labels:
                app: Devops
        spec:
            containers:
                
name: project
                image: berkandocker/project:latest
                ports:
containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: Devops
    namespace: project1
spec:
    selector:
        app: Devops
    ports:
        
protocol: TCP
        port: 80
        targetPort: 5000
  type: LoadBalancer
